spring:
  application:
    name: config-server
  profiles:
    active:
      native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:configs/,configs/config-client
server:
  port: 8888